"""
Entity dataclasses for the Weekly CEO Briefing feature.

This module defines immutable data structures representing business concepts
used throughout the weekly audit process.
"""

from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Optional


@dataclass(frozen=True)
class BusinessGoals:
    """
    Business metrics, targets, and rules that guide audit analysis.

    Source: /Vault/Business_Goals.md (YAML frontmatter)
    """
    revenue_target: Decimal
    current_revenue: Decimal
    key_metrics: list[dict]
    active_projects: list[dict]
    subscription_rules: dict
    last_updated: date
    review_frequency: str

    def __post_init__(self):
        """Validate business goals data."""
        if self.revenue_target <= 0:
            raise ValueError("revenue_target must be positive")
        if self.review_frequency not in ["weekly", "monthly", "quarterly"]:
            raise ValueError("review_frequency must be 'weekly', 'monthly', or 'quarterly'")


@dataclass(frozen=True)
class CompletedTask:
    """
    A task that was completed during the analysis period.

    Source: /Done/*.md files (file modification time + YAML frontmatter)
    """
    name: str
    completion_date: datetime
    file_path: Path
    expected_duration: Optional[timedelta] = None
    actual_duration: Optional[timedelta] = None
    priority: Optional[str] = None
    project: Optional[str] = None

    def __post_init__(self):
        """Validate completed task data."""
        if not self.name:
            raise ValueError("name must not be empty")
        if self.priority and self.priority not in ["high", "medium", "low"]:
            raise ValueError("priority must be 'high', 'medium', or 'low'")
        if self.expected_duration and self.expected_duration <= timedelta(0):
            raise ValueError("expected_duration must be positive")
        if self.actual_duration and self.actual_duration <= timedelta(0):
            raise ValueError("actual_duration must be positive")


@dataclass(frozen=True)
class Transaction:
    """
    A financial transaction (expense or revenue).

    Source: /Accounting/*.csv files
    """
    date: date
    amount: Decimal
    description: str
    source_file: Path
    category: str = "Uncategorized"

    def __post_init__(self):
        """Validate transaction data."""
        if not self.description:
            raise ValueError("description must not be empty")


@dataclass(frozen=True)
class Subscription:
    """
    A detected recurring subscription service.

    Source: Derived from Transaction analysis
    """
    name: str
    amount: Decimal
    last_seen_date: date
    frequency: str
    pattern_matched: str
    transaction_count: int
    flags: list[str] = field(default_factory=list)

    def __post_init__(self):
        """Validate subscription data."""
        if not self.name:
            raise ValueError("name must not be empty")
        if self.amount <= 0:
            raise ValueError("amount must be positive")
        if self.frequency not in ["monthly", "annual"]:
            raise ValueError("frequency must be 'monthly' or 'annual'")


@dataclass(frozen=True)
class TaskBottleneck:
    """
    A task that took significantly longer than expected.

    Source: Derived from CompletedTask entities with duration metadata
    """
    task_name: str
    expected_duration: timedelta
    actual_duration: timedelta
    delay_percent: float
    completion_date: date

    def __post_init__(self):
        """Validate task bottleneck data."""
        if self.delay_percent <= 0:
            raise ValueError("delay_percent must be positive")
        if self.actual_duration <= self.expected_duration:
            raise ValueError("actual_duration must be greater than expected_duration")


@dataclass(frozen=True)
class TransactionSummary:
    """
    Aggregated financial metrics for the analysis period.

    Source: Derived from aggregating Transaction entities
    """
    total_revenue: Decimal
    total_expenses: Decimal
    net_income: Decimal
    transaction_count: int
    subscription_count: int
    top_expense_categories: list[dict]
    period_start: date
    period_end: date

    def __post_init__(self):
        """Validate transaction summary data."""
        if self.total_revenue < 0:
            raise ValueError("total_revenue must be non-negative")
        if self.total_expenses < 0:
            raise ValueError("total_expenses must be non-negative")
        if self.period_end < self.period_start:
            raise ValueError("period_end must be after period_start")


@dataclass(frozen=True)
class CEOBriefing:
    """
    The complete generated briefing report.

    Source: Generated by combining all analyzed data
    """
    week_start: date
    week_end: date
    generated_date: datetime
    executive_summary: str
    revenue_section: dict
    completed_tasks: list[dict]
    bottlenecks: list[dict]
    proactive_suggestions: list[str]
    upcoming_deadlines: list[dict]
    output_path: Path

    def __post_init__(self):
        """Validate CEO briefing data."""
        if self.week_end < self.week_start:
            raise ValueError("week_end must be after week_start")
        if self.generated_date.date() < self.week_end:
            raise ValueError("generated_date must be after week_end")
